### ISSUE TITLE
TypeScript Support?

### ISSUE THREAD

**Issue by n8sabes** [cloudbit-interactive/GSAP-RN#3]
```
ERROR:

Could not find a declaration file for module 'gsap-rn'. '/Users/anon/foo_bar/node_modules/gsap-rn/gsap-rn.js' implicitly has an 'any' type.
  Try `npm install @types/gsap-rn` if it exists or add a new declaration (.d.ts) file containing `declare module 'gsap-rn';`ts(7016)
```
``
``
Is there a way to get TypeScript supported in GSAP-RN?

**Thank you for the awesome library!!**

**Comment by tufik2** [comment]
You can give support to type if you install both libraries. Our library don't implement extra functionalities more than gsap implementation
npm install gsap gsap-rn
