### ISSUE TITLE
tween width %

### ISSUE THREAD

**Issue by Makio64** [cloudbit-interactive/GSAP-RN#4]
This synthax doesnt seems to be supported : 
`gsap.set(percentBar.current,{style:{width:'100%'}})`

Any ideas how to make it work ?

Thanks!

**Comment by Makio64** [comment]
here my current solution but it doesnt looks great in terms of performance : 

    const [percent, setPercent] = useState(0)
    const percentRef= useRef({})
    percentRef.current = percent
    
    useEffect(()=>{
        store.subscribe((e)=>{
            const state = store.getState()
            let done = state.weeks.current.goals[0].done
            let o = {percent:percentRef.current}
            gsap.to(o,{
                duration:1,
                percent:done/quantity * 100,
                onUpdate:(value)=>{setPercent(o.percent)}
            })
        })
    },[])

//...

                <View style={[style.percent,{width:percent+"%"}]}></View>

**Comment by Makio64** [comment]
Just realize after fews tests for better performance, the killTweens(o) is also very important else multiple re-render occur onUpdate...  : 

    const [percent, setPercent] = useState(0)
    const percentRef= useRef({})
    percentRef.current = percent
    let o = {percent:percentRef.current}
    
    useEffect(()=>{
        store.subscribe((e)=>{
            const state = store.getState()
            let done = state.weeks.current.goals[0].done
            gsap.killTweensOf(o)
            gsap.to(o,{
                duration:1,
                percent:done/quantity * 100,
                onUpdate:(value)=>{setPercent(o.percent)}
            })
        })
    },[])

**Comment by tufik2** [comment]
Hi, I am reviewing the issue with %, It will be fixed in next version. For KillTweens you can use AutoKillTweens, It kill tweens automatically for you if the component is unmounted / re-rendered, check the documentation for more info related to AutoKillTweens.

let tweens= {ani1:tweenRef, ani2:tweeRef, ani3:timelineRef}

Render area
`<AutoKillTweens tweens={tweens} />`

Also you can finish a tween anytime using the AutoKillTweens.
```
AutoKillTweens.tweensOf(tweens);
AutoKillTweens.tweensOf(tweens.ani1);
```

**Comment by tufik2** [comment]
Now the library support % values, one recommendation if you will work with %, will be good work only with % values and not jump between % and Integer values.

`
import React, {useState, useEffect} from 'react';
import {View, Text} from "react-native";
import {log, cuppa, Button} from 'src/libs/cuppa/cuppa';
import {AutoKillTweens, gsap, Power2} from 'gsap-rn';

export default function Percentage() {
    let barRef;
    let tweens = {};

    function animate(){
        AutoKillTweens.tweensOf(tweens.tl);
        tweens.tl = gsap.timeline();
        tweens.tl.set(barRef, {style:{width:"0%", backgroundColor:"#FF0"}});
        tweens.tl.to(barRef, {style:{width:"50%", backgroundColor:"#F0F"}, duration: 1, ease:Power2.easeInEaseOut});
        tweens.tl.to(barRef, {style:{width:"25%", alpha:0.5}});
        tweens.tl.to(barRef, {style:{width:"100%", alpha:1, backgroundColor:"#0FF"}, duration: 1, delay:1, ease:Power2.easeInEaseOut});
    }

    return (
        <View style={{flex:1, justifyContent:"center", alignItems:"center"}}>
            <AutoKillTweens tweens={tweens} />
            <View style={[{width:"80%", height:40, borderColor:"#666", borderWidth:1}]}>
                <View ref={ref=>barRef = ref} style={{flex:1, width:"0%"}} />
            </View>
            <Button onPress={animate} text={"Animate Percentage"} style={{marginTop:20}} />
        </View>
    )
}
`
